FROM jketterl/openwebrx-rtltcp
#FROM jketterl/openwebrx:stable

COPY index.html /opt/openwebrx/htdocs/index.html

COPY receiver_top_photo.jpg /var/lib/receiver_top_photo.jpg
COPY settings.json /var/lib/settings.json
